### ISSUE TITLE
markdownlint parse error

### ISSUE THREAD

**Issue by guykisel** [guykisel/inline-plz#159]
```
Installation and running of markdownlint took 47 seconds
Traceback (most recent call last):
  File "/Users/gkisel/.virtualenvs/inline-plz-bot/lib/python2.7/site-packages/inlineplz/linters/__init__.py", line 465, in lint
    linter_messages = config.get('parser')().parse(output)
  File "/Users/gkisel/.virtualenvs/inline-plz-bot/lib/python2.7/site-packages/inlineplz/parsers/markdownlint.py", line 19, in parse
    msgbody = parts[2].strip()
IndexError: list index out of range
(null):0
(null)
 
RangeError: Maximum call stack size exceeded
```

**Comment by guykisel** [comment]
Might need to convert markdownlint to run per file instead of letting it choose what files to run on so that it doesn't dive deep into node_modules.
