### ISSUE TITLE
AttributeError: 'PullRequest' object has no attribute 'as_dict'

### ISSUE THREAD

**Issue by guykisel** [guykisel/inline-plz#181]
```
5848 lint messages found
Traceback (most recent call last):
  File "/usr/bin/inline-plz", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/inlineplz/main.py", line 55, in main
    result = inline(args)
  File "/usr/lib/python2.7/site-packages/inlineplz/main.py", line 150, in inline
    if my_interface.post_messages(messages, args.max_comments) and not args.zero_exit:
  File "/usr/lib/python2.7/site-packages/inlineplz/interfaces/github.py", line 59, in post_messages
    if self.out_of_date():
  File "/usr/lib/python2.7/site-packages/inlineplz/interfaces/github.py", line 45, in out_of_date
    current_sha = pull_request.as_dict()['head']['sha']
AttributeError: 'PullRequest' object has no attribute 'as_dict'
```

**Comment by guykisel** [comment]
fixed in #179
