### ISSUE TITLE
bandit failing to parse properly

### ISSUE THREAD

**Issue by guykisel** [guykisel/inline-plz#377]
```Running of bandit took 7 seconds
Parsing bandit output failed:
Traceback (most recent call last):
  File "/home/travis/build/guykisel/inline-plz/inlineplz/linter_runner.py", line 371, in run_linter
    linter_messages = config.get("parser")().parse(output)
  File "/home/travis/build/guykisel/inline-plz/inlineplz/linters/bandit.py", line 44, in parse
    for msgdata in json.loads(lint_data_cleaned).get("results"):
AttributeError: 'int' object has no attribute 'get'
[main]	INFO	profile include tests: None
[main]	INFO	profile exclude tests: None
[main]	INFO	cli include tests: None
[main]	INFO	cli exclude tests: None
55 [0.. 50.. ]
{
  "errors": []
  "generated_at": "2018-09-18T23:04:05Z"
  "metrics": {
    "./inlineplz/__init__.py": {
      "CONFIDENCE.HIGH": 0.0
      "CONFIDENCE.LOW": 0.0
      "CONFIDENCE.MEDIUM": 0.0
      "CONFIDENCE.UNDEFINED": 0.0
      "SEVERITY.HIGH": 0.0
      "SEVERITY.LOW": 0.0
      "SEVERITY.MEDIUM": 0.0
      "SEVERITY.UNDEFINED": 0.0
      "loc": 4
      "nosec": 0
    }```

**Comment by guykisel** [comment]
fixed in #399
